### ISSUE TITLE
Export as a bmap.txt

### ISSUE THREAD

**Issue by ShaigroRB** [ShaigroRB/nabe#4]
# Description

From a list of lines representing a bmap.txt, save those lines in a file.

Input: `["Boring title", 1, -1, { ... }, { ... }]`

Output: bmap.txt containing the following lines:
```
Boring title
1
-1
{ ... }
{ ... }
```

## Tasks

- [ ] Add an option in a menu "File" called "Export as bmap.txt"
- [ ] Open a dialog to choose where to export the file.
- [ ] Clicking "Ok" export the file to the chosen folder

# Definition of done

- [ ] I can export as a bmap.txt in a specific folder
  - This can be tested by importing a bmap.txt and then exporting it. It should be the same file.
