### ISSUE TITLE
Setup PixiJS & draw a grid of 128x128px

### ISSUE THREAD

**Issue by ShaigroRB** [ShaigroRB/nabe#5]
# Description

[PixiJS](https://github.com/pixijs/pixijs) is the JS library that will be used to draw the elements and handle all the interaction with the map itself.

Selecting options or assets or tiles will be done in a separate sidebar.

## Tasks

- [ ] Install PixiJS
- [x] Research if it is worth using `pixi-react`
   - `pixi-react` lets you use declarative style
   - it doesn't support everything vanilla pixi does
- [ ] Draw a grid of 128x128px

# Definition of done

- [ ] The app displays a grid
